apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: lokesh3721/node-app:latest
          volumeMounts:
            - name: database-connection
              mountPath: /opt
          ports:
            - containerPort: 3000
      volumes:
        - name: database-connection
          configMap:
            name: node-config
