apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: lokesh3721/node-app:latest
          env:
            - name: db-port
              valueFrom:
                configMapKeyRef:
                  name: node-config # The ConfigMap this value comes from.
                  key: db-port # The key to fetch.
          ports:
            - containerPort: 3000
