
pipeline{
  agent none 
  stages {
    stage('Back-end'){
      agent{
        docker {
          image 'node:latest'
        }
      }
      steps{
        sh 'git clone https://github.com/lokeshsingh3721/devops'
        sh 'cd devops/ci-cd && node index.js'
      }
    }
  }
}
